services:
  - type: web
    name: ats-resume-app
    env: docker
    plan: free
    region: oregon
    envVars:
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: PORT
        value: "8000"
      - key: DJANGO_SETTINGS_MODULE
        value: ats_resume_app.settings