# Generated by Django 4.2.7 on 2025-06-06 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_remove_skill_unique_skill_per_resume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'LLM Settings',
                'verbose_name_plural': 'LLM Settings',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.resume'),
        ),
    ]
