# Generated by Django 4.2.7 on 2025-06-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_add_resume_fk_to_downloadlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='limit_15_days',
            field=models.PositiveIntegerField(default=3, help_text='Max downloads in any rolling 15-day window'),
        ),
        migrations.AddField(
            model_name='profile',
            name='limit_month',
            field=models.PositiveIntegerField(default=6, help_text='Max downloads in a calendar month'),
        ),
    ]
